# Generated by Django 5.0.6 on 2024-07-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_experience_rename_experiencee_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='skill',
            new_name='univercity_name',
        ),
    ]
