# Generated by Django 5.0.6 on 2024-07-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_skill_education_univercity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='address',
            new_name='depertment',
        ),
    ]
